#!/usr/bin/env bash
# Unattended Installation Module for VMSwarm
# Provides functions for automatic Linux Mint installation via preseed files

# Generate preseed file for unattended Debian/Linux Mint installation
# Usage: generate_preseed <hostname> <username> <password> <output_file>
generate_preseed() {
  local hostname="$1"
  local username="$2"
  local password="$3"
  local output_file="$4"
  
  # Hash the password using mkpasswd (install if needed)
  if ! command -v mkpasswd >/dev/null 2>&1; then
    log_info "Installing whois package for password hashing..."
    sudo apt update >/dev/null 2>&1
    sudo apt install -y whois >/dev/null 2>&1
  fi
  
  local password_hash
  password_hash=$(echo "$password" | mkpasswd -s -m sha-512)
  
  # Create preseed file
  cat > "$output_file" << EOF
# Unattended Linux Mint Installation Preseed File
# Generated by VMSwarm

# Localization
d-i debian-installer/language string en
d-i debian-installer/country string US
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us

# Network configuration
d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string $hostname
d-i netcfg/get_domain string localdomain
d-i netcfg/wireless_wep string

# Mirror settings
d-i mirror/country string US
d-i mirror/http/hostname string archive.ubuntu.com
d-i mirror/http/directory string /ubuntu
d-i mirror/http/proxy string
d-i mirror/suite string focal

# Clock and time zone
d-i time/zone string UTC
d-i clock-setup/utc boolean true
d-i clock-setup/ntp boolean true
d-i clock-setup/ntp-server string ntp.ubuntu.com

# Disk partitioning
d-i partman-auto/method string lvm
d-i partman-lvm/device_remove_lvm boolean true
d-i partman-md/device_remove_md boolean true
d-i partman-lvm/confirm boolean true
d-i partman-lvm/confirm_nooverwrite boolean true
d-i partman-auto-lvm/guided_size string max
d-i partman-auto/choose_recipe select atomic
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true

# Apt setup
d-i apt-setup/restricted boolean true
d-i apt-setup/universe boolean true
d-i apt-setup/multiverse boolean true
d-i apt-setup/backports boolean true

# Package selection
tasksel tasksel/first multiselect ubuntu-desktop
d-i pkgsel/install-language-support boolean false
d-i pkgsel/language-pack-patterns string
d-i pkgsel/include string openssh-server
d-i pkgsel/upgrade select full-upgrade

# User configuration
d-i passwd/user-fullname string $username
d-i passwd/username string $username
d-i passwd/user-password-crypted string $password_hash
d-i passwd/root-password-crypted string $password_hash

# GRUB boot loader
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean false
d-i grub-installer/bootdev string default

# Finish installation
d-i finish-install/reboot_in_progress note
d-i debian-installer/exit/poweroff boolean false

# Additional settings for unattended installation
d-i preseeding/early_command string \
  echo "Preseed: Starting unattended installation..." > /dev/console
d-i preseed/late_command string \
  in-target sh -c 'echo "root:$password_hash" | chpasswd -e'
EOF

  if [[ -f "$output_file" ]]; then
    log_info "Preseed file generated: $output_file"
    return 0
  else
    log_err 105 "Failed to generate preseed file"
  fi
}

# Prompt user for installation type and gather required information
# Usage: prompt_install_type <returns install_type in variable>
prompt_install_type() {
  echo ""
  echo "============================================"
  echo "Linux Mint Installation Mode"
  echo "============================================"
  echo "Auto-install will run the installer unattended using a preseed file."
  echo ""
  
  local choice
  read -p "Do you want to auto install this VM? [y/N]: " choice
  choice="${choice:-n}"
  
  case "${choice,,}" in
    y|yes)
      echo "Auto-install selected."
      return 0  # Return 0 for auto-install
      ;;
    *)
      echo "Manual install selected."
      return 1  # Return 1 for manual install
      ;;
  esac
}

# Gather required information for unattended installation
# Usage: prompt_install_credentials <returns hostname, username, password in variables>
prompt_install_credentials() {
  local default_hostname="mint-vm"
  local default_username="user"
  
  echo ""
  echo "============================================"
  echo "Installation Configuration"
  echo "============================================"
  
  read -p "Enter hostname (default '$default_hostname'): " hostname
  hostname="${hostname:-$default_hostname}"
  
  read -p "Enter default username (default '$default_username'): " username
  username="${username:-$default_username}"
  
  # Securely read password
  local password1 password2
  while true; do
    read -sp "Enter password: " password1
    echo ""
    read -sp "Confirm password: " password2
    echo ""
    
    if [[ "$password1" == "$password2" ]]; then
      if [[ -z "$password1" ]]; then
        echo "Error: Password cannot be empty. Please try again."
        continue
      fi
      break
    else
      echo "Error: Passwords do not match. Please try again."
    fi
  done
  
  # Export variables for use in parent shell
  export INSTALL_HOSTNAME="$hostname"
  export INSTALL_USERNAME="$username"
  export INSTALL_PASSWORD="$password1"
}

# Prepare an extracted install tree from an ISO for virt-install --location
# Usage: prepare_install_tree <iso_path>
prepare_install_tree() {
  local iso_path="$1"
  local work_dir="/tmp/vmswarm_install_tree_$$"

  if ! command -v xorriso >/dev/null 2>&1; then
    log_info "Installing xorriso for ISO extraction..." >/dev/null 2>&1
    sudo apt update >/dev/null 2>&1
    sudo apt install -y xorriso >/dev/null 2>&1
  fi

  mkdir -p "$work_dir"
  log_info "Extracting install tree from ISO..." >/dev/null 2>&1
  if ! xorriso -osirrox on -indev "$iso_path" -extract / "$work_dir" >/dev/null 2>&1; then
    rm -rf "$work_dir"
    log_err 105 "Failed to extract install tree from ISO: $iso_path"
  fi

  echo "$work_dir"
}

# Modify ISO to include preseed file for unattended installation
# Usage: inject_preseed_into_iso <iso_path> <preseed_file> <output_iso>
inject_preseed_into_iso() {
  local iso_path="$1"
  local preseed_file="$2"
  local output_iso="$3"
  local work_dir="/tmp/vmswarm_iso_work_$$"
  
  log_info "Preparing to inject preseed file into ISO..."
  
  # Check for required tools
  if ! command -v xorriso >/dev/null 2>&1; then
    log_info "Installing xorriso for ISO modification..."
    sudo apt update >/dev/null 2>&1
    sudo apt install -y xorriso >/dev/null 2>&1
  fi
  
  mkdir -p "$work_dir"
  
  # Extract ISO
  log_info "Extracting ISO contents..."
  xorriso -osirrox on -indev "$iso_path" -extract / "$work_dir" 2>/dev/null || {
    log_err 105 "Failed to extract ISO. Ensure xorriso is installed."
  }
  
  # Copy preseed file to ISO
  cp "$preseed_file" "$work_dir/preseed.cfg"
  log_info "Injected preseed file into ISO"
  
  # Rebuild ISO with preseed
  log_info "Rebuilding ISO with preseed file..."
  xorriso -as mkisofs -r -V "Linux Mint Auto" \
    -b isolinux/isolinux.bin -c isolinux/boot.cat \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -o "$output_iso" "$work_dir" 2>/dev/null || {
    log_err 105 "Failed to rebuild ISO with preseed"
  }
  
  # Cleanup
  rm -rf "$work_dir"
  
  if [[ -f "$output_iso" ]]; then
    log_info "Modified ISO created: $output_iso"
    return 0
  else
    log_err 105 "Failed to create modified ISO"
  fi
}

# Create cloud-init user-data file for unattended setup
# Usage: generate_cloudinit_userdata <hostname> <username> <password> <output_file>
generate_cloudinit_userdata() {
  local hostname="$1"
  local username="$2"
  local password="$3"
  local output_file="$4"
  
  # Hash password for cloud-init
  local password_hash
  password_hash=$(echo "$password" | mkpasswd -s -m sha-512)
  
  cat > "$output_file" << EOF
#cloud-config
hostname: $hostname
fqdn: $hostname.localdomain
package_update: true
package_upgrade: true
packages:
  - openssh-server
  - net-tools

users:
  - name: $username
    groups: sudo
    shell: /bin/bash
    passwd: $password_hash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false

ssh:
  enabled: true
  port: 22

final_message: "Cloud-init has finished initialization in \$TIME seconds"
EOF

  if [[ -f "$output_file" ]]; then
    log_info "Cloud-init user-data file generated: $output_file"
    return 0
  else
    log_err 105 "Failed to generate cloud-init user-data file"
  fi
}

# Get preseed file path for given VM
# Usage: get_preseed_path <vm_name>
get_preseed_path() {
  local vm_name="$1"
  echo "${VMSWARM_IMAGE_DIR}/${vm_name}-preseed.cfg"
}

# Clean up preseed files
# Usage: cleanup_preseed <vm_name>
cleanup_preseed() {
  local vm_name="$1"
  local preseed_file
  preseed_file=$(get_preseed_path "$vm_name")
  
  if [[ -f "$preseed_file" ]]; then
    rm -f "$preseed_file"
    log_info "Cleaned up preseed file: $preseed_file"
  fi
}
